from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base

from database.connection.DbConnection import pulse_db_schema

metadata = MetaData(schema=pulse_db_schema)
Base = declarative_base(metadata=metadata)


class PrimaryData(Base):
    __tablename__ = 'primary_data'
    __schemaname__ = pulse_db_schema
    equities_hash = Column(String, primary_key=True, nullable=False)
    script_name = Column(String, nullable=False)
    trade_date = Column(Date, nullable=False)
    iq_eps_est_ciq = Column(Float, nullable=True)
    iq_pe_excl_fwd_ciq = Column(Float, nullable=True)
    iq_eps_median_est_ciq = Column(Float, nullable=True)
    iq_revenue_median_est_ciq_fq_1 = Column(Float, nullable=True)
    iq_eps_est_ciq_fy_1 = Column(Float, nullable=True)
    iq_eps_high_est_ciq_fy_1 = Column(Float, nullable=True)
    iq_eps_low_est_ciq_fy_1 = Column(Float, nullable=True)
    iq_eps_est_ciq_fy_2 = Column(Float, nullable=True)
    iq_basic_eps_excl = Column(Float, nullable=True)
    iq_capex = Column(Float, nullable=True)
    iq_cash_equiv = Column(Float, nullable=True)
    iq_cash_interest = Column(Float, nullable=True)
    iq_cash_oper = Column(Float, nullable=True)
    iq_cash_st_invest = Column(Float, nullable=True)
    iq_cash_taxes = Column(Float, nullable=True)
    iq_change_net_working_capital = Column(Float, nullable=True)
    iq_cogs = Column(Float, nullable=True)
    iq_common_issued = Column(Float, nullable=True)
    iq_common_rep = Column(Float, nullable=True)
    iq_da_cf = Column(Float, nullable=True)
    iq_ebit = Column(Float, nullable=True)
    iq_ebitda = Column(Float, nullable=True)
    iq_gp = Column(Float, nullable=True)
    iq_inventory = Column(Float, nullable=True)
    iq_lt_debt = Column(Float, nullable=True)
    iq_minority_interest = Column(Float, nullable=True)
    iq_ni = Column(Float, nullable=True)
    iq_ni_avail_excl = Column(Float, nullable=True)
    iq_oper_inc = Column(Float, nullable=True)
    iq_pref_equity = Column(Float, nullable=True)
    iq_pref_issued = Column(Float, nullable=True)
    iq_pref_rep = Column(Float, nullable=True)
    iq_total_assets = Column(Float, nullable=True)
    iq_total_cl = Column(Float, nullable=True)
    iq_total_debt = Column(Float, nullable=True)
    iq_ebitda_int = Column(Float, nullable=True)
    iq_total_common_equity = Column(Float, nullable=True)
    iq_total_debt_current = Column(Float, nullable=True)
    iq_total_debt_issued = Column(Float, nullable=True)
    iq_total_debt_repaid = Column(Float, nullable=True)
    iq_total_div_paid_cf = Column(Float, nullable=True)
    iq_total_equity = Column(Float, nullable=True)
    iq_total_rev = Column(Float, nullable=True)
    iq_avg_broker_rec_no_ciq = Column(Float, nullable=True)
    iq_dividend_yield = Column(Float, nullable=True)
    iq_est_eps_growth_5yr_ciq = Column(Float, nullable=True)
    iq_marketcap = Column(Float, nullable=True)
    iq_price_target_ciq = Column(Float, nullable=True)
    iq_sharesoutstanding = Column(Float, nullable=True)
