portfolio: PULSE_BACKTEST
strategy: auxerre_signal
result_path: /Users/ashwin/PycharmProjects/trading-platform/backtest/results/

transaction_cost: 0.0015

run_parameters:
  start_date: 2018-01-01
  end_date: 2024-11-30
  training_days: 50
  look_back_days: 200

model_parameters:
  short_exposure: 1
  margin_rate: 0.3
  maintainance_margin: 0.1
  leverage: 1
  option_moneyness: 1.02